package krypto

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/argon2"
)

const saltLen = 16

var (
	// ErrInvalidInput indicates invalid input was provided.
	ErrInvalidInput = errors.New("invalid input")
)

const (
	variant = "argon2id"
	// use the recommended parameters for argon2 password hashing according to OWASP:
	// https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
	memoryKiB   = 46 * 1024
	iterations  = 1
	parallelism = 1
)

// Argon2Hash is a hash generated by the Argon2 Hashing Algorithm.
type Argon2Hash struct {
	Variant     string
	Version     uint32
	MemoryKiB   uint32
	Iterations  uint32
	Parallelism uint8
	Salt        []byte
	Hash        []byte
}

// HashArgon2 hashes a byte slice using the argon2id algorithm.
func HashArgon2(b []byte) (Argon2Hash, error) {
	// First we generate a salt.
	salt, err := genRandomBytes(saltLen)
	if err != nil {
		return Argon2Hash{}, fmt.Errorf("failed to generate salt: %w", err)
	}

	return hashArgon2WithSalt(b, salt)
}

// HashArgon2WithKey hashes a byte slice using the argon2id algorithm and uses the provided key as a salt.
func HashArgon2WithKey(b []byte, salt Key) (Argon2Hash, error) {
	if len(salt.value) <= saltLen {
		return Argon2Hash{}, fmt.Errorf("salt too short: %w", ErrInvalidInput)
	}

	return hashArgon2WithSalt(b, salt.value[:saltLen])
}

// hashArgon2WithSalt hashes a byte slice using the argon2id algorithm with the provided salt.
func hashArgon2WithSalt(b []byte, salt []byte) (Argon2Hash, error) {
	if len(b) == 0 {
		return Argon2Hash{}, fmt.Errorf("empty byte slice: %w", ErrInvalidInput)
	}

	// Then we hash the bytes.
	hash := argon2.IDKey(b, salt, iterations, memoryKiB, parallelism, keyLen)

	return Argon2Hash{
		Variant:     variant,
		Version:     argon2.Version,
		MemoryKiB:   memoryKiB,
		Iterations:  iterations,
		Parallelism: parallelism,
		Salt:        salt,
		Hash:        hash,
	}, nil
}

// ParseArgon2Hash parses an argon2 hash from the string representation provided by the String method.
func ParseArgon2Hash(txt string) (Argon2Hash, error) {
	// Split the string into its components.
	vals := strings.Split(txt, "$")
	if len(vals) != 6 {
		return Argon2Hash{}, fmt.Errorf("wrong number of components: %w", ErrInvalidInput)
	}

	h := Argon2Hash{}
	for i, v := range vals {
		if !parseComponent(i, v, &h) {
			return Argon2Hash{}, fmt.Errorf("failed to parse component %d: %w", i, ErrInvalidInput)
		}
	}

	return h, nil
}

// parseComponent parses a single of a textual argon2 hash representation.
// i is the component index, v is the component value and h is the hash to populate.
// return false to indicate that the component was not parsed successfully.
func parseComponent(i int, v string, h *Argon2Hash) bool {
	switch i {
	case 0:
		return v == ""
	case 1:
		h.Variant = v
		return v == variant
	case 2:
		_, err := fmt.Sscanf(v, "v=%d", &h.Version)
		return err == nil && h.Version == argon2.Version
	case 3:
		_, err := fmt.Sscanf(v, "m=%d,t=%d,p=%d", &h.MemoryKiB, &h.Iterations, &h.Parallelism)
		return err == nil
	case 4:
		salt, err := base64.RawStdEncoding.DecodeString(v)
		h.Salt = salt
		return err == nil
	case 5:
		hash, err := base64.RawStdEncoding.DecodeString(v)
		h.Hash = hash
		return err == nil
	}

	return false
}

// MatchBytes checks if the hash matches the given byte slice.
func (h Argon2Hash) MatchBytes(b []byte) bool {
	hash := argon2.IDKey(b, h.Salt, h.Iterations, h.MemoryKiB, h.Parallelism, uint32(len(h.Hash)))
	return subtle.ConstantTimeCompare(hash, h.Hash) == 1
}

// String returns the string representation of the hash.
func (h Argon2Hash) String() string {
	b64Hash := base64.RawStdEncoding.EncodeToString(h.Hash)
	b64Salt := base64.RawStdEncoding.EncodeToString(h.Salt)

	return fmt.Sprintf("$%s$v=%d$m=%d,t=%d,p=%d$%s$%s", h.Variant, h.Version, h.MemoryKiB, h.Iterations, h.Parallelism, b64Salt, b64Hash)
}

// MarshalText implements the encoding.TextMarshaler interface.
func (h Argon2Hash) MarshalText() ([]byte, error) {
	return []byte(h.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (h *Argon2Hash) UnmarshalText(text []byte) error {
	parsed, err := ParseArgon2Hash(string(text))
	if err != nil {
		return err
	}
	*h = parsed
	return nil
}

// Scan implements the sql.Scanner interface.
func (h *Argon2Hash) Scan(v any) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("can only scan strings, got %T", v)
	}

	parsed, err := ParseArgon2Hash(s)
	if err != nil {
		return err
	}

	*h = parsed

	return nil
}

func genRandomBytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	if err != nil {
		return nil, fmt.Errorf("failed to read random bytes: %w", err)
	}

	return b, nil
}
